import type { Question, SectionId, PartNumber } from "@/lib/types";

// ============================================================
// Section Metadata
// ============================================================

export const SECTIONS = [
  {
    id: "demographics" as SectionId,
    label: "Demographics & Founder Context",
    part: 1 as PartNumber,
    intro:
      "First, some background about you and your company. This helps us compare results across different founder profiles.",
  },
  {
    id: "adhd" as SectionId,
    label: "ADHD Screening",
    part: 1 as PartNumber,
    intro:
      "These questions screen for attention-related traits. Answer based on your experience over the past 6 months.",
  },
  {
    id: "autism" as SectionId,
    label: "Autism Screening",
    part: 1 as PartNumber,
    intro:
      "These questions assess social communication and sensory processing patterns. There are no right or wrong answers.",
  },
  {
    id: "dark_triad" as SectionId,
    label: "Personality Traits",
    part: 1 as PartNumber,
    intro:
      "These questions measure personality traits that are common in competitive, high-stakes environments. There are no right or wrong answers.",
  },
  {
    id: "depression" as SectionId,
    label: "Depression Screening",
    part: 2 as PartNumber,
    intro: "These questions ask about your mood over the last 2 weeks.",
  },
  {
    id: "anxiety" as SectionId,
    label: "Anxiety Screening",
    part: 2 as PartNumber,
    intro:
      "These questions ask about worry and anxiety over the last 2 weeks.",
  },
  {
    id: "founder_stress" as SectionId,
    label: "Founder-Specific Stress",
    part: 2 as PartNumber,
    intro: "These questions are specific to the founder experience.",
  },
  {
    id: "treatment" as SectionId,
    label: "Treatment & Support",
    part: 3 as PartNumber,
    intro:
      "Finally, some questions about mental health support you've used, past and present.",
  },
];

// ============================================================
// Section Order
// ============================================================

export const SECTION_ORDER: SectionId[] = [
  "demographics",
  "adhd",
  "autism",
  "dark_triad",
  "depression",
  "anxiety",
  "founder_stress",
  "treatment",
];

// ============================================================
// All Questions
// ============================================================

export const QUESTIONS: Question[] = [
  // --------------------------------------------------------
  // PART 1: ABOUT YOU
  // --------------------------------------------------------

  // === Demographics ===
  {
    id: "demo_age",
    section: "demographics",
    part: 1,
    text: "What is your age?",
    type: "number",
    required: true,
    instrument: null,
  },
  {
    id: "demo_gender",
    section: "demographics",
    part: 1,
    text: "What is your gender?",
    type: "single_select",
    options: ["Man", "Woman", "Non-binary", "Prefer not to say", "Self-describe"],
    required: true,
    instrument: null,
  },
  {
    id: "demo_ethnicity",
    section: "demographics",
    part: 1,
    text: "What is your race/ethnicity?",
    type: "multi_select",
    options: [
      "Asian",
      "Black/African American",
      "Hispanic/Latino",
      "Middle Eastern/North African",
      "Native American/Alaska Native",
      "Pacific Islander",
      "White",
      "Prefer not to say",
      "Self-describe",
    ],
    required: false,
    instrument: null,
  },
  {
    id: "demo_company_stage",
    section: "demographics",
    part: 1,
    text: "What stage is your company?",
    type: "single_select",
    options: [
      "Idea stage",
      "Pre-seed",
      "Seed",
      "Series A",
      "Series B+",
      "Exited",
      "Shut down",
    ],
    required: true,
    instrument: null,
  },
  {
    id: "demo_founder_type",
    section: "demographics",
    part: 1,
    text: "Are you a solo founder or co-founder?",
    type: "single_select",
    options: ["Solo founder", "Co-founder"],
    required: true,
    instrument: null,
  },
  {
    id: "demo_years_founding",
    section: "demographics",
    part: 1,
    text: "How many years since you founded your company?",
    type: "number",
    required: true,
    instrument: null,
  },
  {
    id: "demo_industry",
    section: "demographics",
    part: 1,
    text: "What is your industry vertical?",
    type: "single_select",
    options: [
      "SaaS/Software",
      "Fintech",
      "Healthcare/Biotech",
      "Consumer",
      "E-commerce",
      "AI/ML",
      "Hardware",
      "Marketplace",
      "Climate/Energy",
      "Education",
      "Other",
    ],
    required: true,
    instrument: null,
  },
  {
    id: "demo_team_size",
    section: "demographics",
    part: 1,
    text: "What is your current team size?",
    type: "single_select",
    options: ["Just me", "2-5", "6-15", "16-50", "51-200", "200+"],
    required: true,
    instrument: null,
  },
  {
    id: "demo_funding",
    section: "demographics",
    part: 1,
    text: "How much total funding have you raised?",
    type: "single_select",
    options: [
      "Bootstrapped/No funding",
      "Under $500K",
      "$500K-$2M",
      "$2M-$5M",
      "$5M-$15M",
      "$15M-$50M",
      "$50M+",
    ],
    required: true,
    instrument: null,
  },
  {
    id: "demo_cofounder_strain",
    section: "demographics",
    part: 1,
    text: "Would you describe your co-founder relationship as strained?",
    type: "yes_no",
    required: true,
    instrument: null,
    conditionalOn: "demo_founder_type",
    conditionalValue: "Co-founder",
  },

  // === ADHD: ASRS-v1.1 Part A ===
  {
    id: "adhd_asrs_1",
    section: "adhd",
    part: 1,
    text: "How often do you have trouble wrapping up the final details of a project, once the challenging parts have been done?",
    type: "likert5",
    options: ["Never", "Rarely", "Sometimes", "Often", "Very Often"],
    required: true,
    instrument: "ASRS",
  },
  {
    id: "adhd_asrs_2",
    section: "adhd",
    part: 1,
    text: "How often do you have difficulty getting things in order when you have to do a task that requires organization?",
    type: "likert5",
    options: ["Never", "Rarely", "Sometimes", "Often", "Very Often"],
    required: true,
    instrument: "ASRS",
  },
  {
    id: "adhd_asrs_3",
    section: "adhd",
    part: 1,
    text: "How often do you have problems remembering appointments or obligations?",
    type: "likert5",
    options: ["Never", "Rarely", "Sometimes", "Often", "Very Often"],
    required: true,
    instrument: "ASRS",
  },
  {
    id: "adhd_asrs_4",
    section: "adhd",
    part: 1,
    text: "When you have a task that requires a lot of thought, how often do you avoid or delay getting started?",
    type: "likert5",
    options: ["Never", "Rarely", "Sometimes", "Often", "Very Often"],
    required: true,
    instrument: "ASRS",
  },
  {
    id: "adhd_asrs_5",
    section: "adhd",
    part: 1,
    text: "How often do you fidget or squirm with your hands or feet when you have to sit down for a long time?",
    type: "likert5",
    options: ["Never", "Rarely", "Sometimes", "Often", "Very Often"],
    required: true,
    instrument: "ASRS",
  },
  {
    id: "adhd_asrs_6",
    section: "adhd",
    part: 1,
    text: "How often do you feel overly active and compelled to do things, like you were driven by a motor?",
    type: "likert5",
    options: ["Never", "Rarely", "Sometimes", "Often", "Very Often"],
    required: true,
    instrument: "ASRS",
  },

  // === ADHD: Custom ===
  {
    id: "adhd_custom_1",
    section: "adhd",
    part: 1,
    text: "How often do you start new projects before finishing existing ones?",
    type: "likert5",
    options: ["Never", "Rarely", "Sometimes", "Often", "Very Often"],
    required: true,
    instrument: null,
  },
  {
    id: "adhd_custom_2",
    section: "adhd",
    part: 1,
    text: "Do you find operational/repetitive tasks significantly harder than strategic/creative work?",
    type: "likert5",
    options: ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
    required: true,
    instrument: null,
  },
  {
    id: "adhd_custom_3",
    section: "adhd",
    part: 1,
    text: "Have you been diagnosed with ADHD?",
    type: "single_select",
    options: ["Yes", "No", "Suspected but not diagnosed"],
    required: true,
    instrument: null,
  },
  {
    id: "adhd_custom_4",
    section: "adhd",
    part: 1,
    text: "Are you currently receiving treatment for ADHD?",
    type: "yes_no",
    required: true,
    instrument: null,
    conditionalOn: "adhd_custom_3",
    conditionalValue: ["Yes", "Suspected but not diagnosed"],
  },

  // === Autism: AQ-10 ===
  {
    id: "autism_aq10_1",
    section: "autism",
    part: 1,
    text: "I often notice small sounds when others do not.",
    type: "likert4",
    options: [
      "Definitely Agree",
      "Slightly Agree",
      "Slightly Disagree",
      "Definitely Disagree",
    ],
    required: true,
    instrument: "AQ-10",
  },
  {
    id: "autism_aq10_2",
    section: "autism",
    part: 1,
    text: "I usually concentrate more on the whole picture, rather than the small details.",
    type: "likert4",
    options: [
      "Definitely Agree",
      "Slightly Agree",
      "Slightly Disagree",
      "Definitely Disagree",
    ],
    required: true,
    instrument: "AQ-10",
  },
  {
    id: "autism_aq10_3",
    section: "autism",
    part: 1,
    text: "I find it easy to do more than one thing at once.",
    type: "likert4",
    options: [
      "Definitely Agree",
      "Slightly Agree",
      "Slightly Disagree",
      "Definitely Disagree",
    ],
    required: true,
    instrument: "AQ-10",
  },
  {
    id: "autism_aq10_4",
    section: "autism",
    part: 1,
    text: "If there is an interruption, I can switch back to what I was doing very quickly.",
    type: "likert4",
    options: [
      "Definitely Agree",
      "Slightly Agree",
      "Slightly Disagree",
      "Definitely Disagree",
    ],
    required: true,
    instrument: "AQ-10",
  },
  {
    id: "autism_aq10_5",
    section: "autism",
    part: 1,
    text: "I find it easy to 'read between the lines' when someone is talking to me.",
    type: "likert4",
    options: [
      "Definitely Agree",
      "Slightly Agree",
      "Slightly Disagree",
      "Definitely Disagree",
    ],
    required: true,
    instrument: "AQ-10",
  },
  {
    id: "autism_aq10_6",
    section: "autism",
    part: 1,
    text: "I know how to tell if someone listening to me is getting bored.",
    type: "likert4",
    options: [
      "Definitely Agree",
      "Slightly Agree",
      "Slightly Disagree",
      "Definitely Disagree",
    ],
    required: true,
    instrument: "AQ-10",
  },
  {
    id: "autism_aq10_7",
    section: "autism",
    part: 1,
    text: "When I'm reading a story I find it difficult to work out the characters' intentions.",
    type: "likert4",
    options: [
      "Definitely Agree",
      "Slightly Agree",
      "Slightly Disagree",
      "Definitely Disagree",
    ],
    required: true,
    instrument: "AQ-10",
  },
  {
    id: "autism_aq10_8",
    section: "autism",
    part: 1,
    text: "I like to collect information about categories of things (e.g., types of car, types of bird, types of train, types of plant, etc.).",
    type: "likert4",
    options: [
      "Definitely Agree",
      "Slightly Agree",
      "Slightly Disagree",
      "Definitely Disagree",
    ],
    required: true,
    instrument: "AQ-10",
  },
  {
    id: "autism_aq10_9",
    section: "autism",
    part: 1,
    text: "I find it easy to work out what someone is thinking or feeling just by looking at their face.",
    type: "likert4",
    options: [
      "Definitely Agree",
      "Slightly Agree",
      "Slightly Disagree",
      "Definitely Disagree",
    ],
    required: true,
    instrument: "AQ-10",
  },
  {
    id: "autism_aq10_10",
    section: "autism",
    part: 1,
    text: "I find it difficult to work out people's intentions.",
    type: "likert4",
    options: [
      "Definitely Agree",
      "Slightly Agree",
      "Slightly Disagree",
      "Definitely Disagree",
    ],
    required: true,
    instrument: "AQ-10",
  },

  // === Autism: Custom ===
  {
    id: "autism_custom_1",
    section: "autism",
    part: 1,
    text: "Do you find networking events draining in a way that goes beyond normal introversion?",
    type: "likert5",
    options: ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
    required: true,
    instrument: null,
  },
  {
    id: "autism_custom_2",
    section: "autism",
    part: 1,
    text: "Have colleagues or co-founders commented on your communication style being unusual?",
    type: "likert5",
    options: ["Never", "Rarely", "Sometimes", "Often", "Very Often"],
    required: true,
    instrument: null,
  },
  {
    id: "autism_custom_3",
    section: "autism",
    part: 1,
    text: "Have you been diagnosed with autism/ASD?",
    type: "single_select",
    options: ["Yes", "No", "Suspected but not diagnosed"],
    required: true,
    instrument: null,
  },
  {
    id: "autism_custom_4",
    section: "autism",
    part: 1,
    text: "Are you currently receiving support related to autism?",
    type: "yes_no",
    required: true,
    instrument: null,
    conditionalOn: "autism_custom_3",
    conditionalValue: ["Yes", "Suspected but not diagnosed"],
  },

  // === Dark Triad: SD3 - Machiavellianism ===
  {
    id: "sd3_mach_1",
    section: "dark_triad",
    part: 1,
    text: "It's not wise to tell your secrets.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_mach_2",
    section: "dark_triad",
    part: 1,
    text: "I like to use clever manipulation to get my way.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_mach_3",
    section: "dark_triad",
    part: 1,
    text: "Whatever it takes, you must get the important people on your side.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_mach_4",
    section: "dark_triad",
    part: 1,
    text: "Avoid direct conflict with others because they may be useful in the future.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_mach_5",
    section: "dark_triad",
    part: 1,
    text: "It's wise to keep track of information that you can use against people later.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_mach_6",
    section: "dark_triad",
    part: 1,
    text: "You should wait for the right time to get back at people.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_mach_7",
    section: "dark_triad",
    part: 1,
    text: "There are things you should hide from other people to preserve your reputation.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_mach_8",
    section: "dark_triad",
    part: 1,
    text: "Make sure your plans benefit yourself, not others.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_mach_9",
    section: "dark_triad",
    part: 1,
    text: "Most people can be manipulated.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },

  // === Dark Triad: SD3 - Narcissism ===
  {
    id: "sd3_narc_1",
    section: "dark_triad",
    part: 1,
    text: "People see me as a natural leader.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_narc_2",
    section: "dark_triad",
    part: 1,
    text: "I hate being the center of attention.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_narc_3",
    section: "dark_triad",
    part: 1,
    text: "Many group activities tend to be dull without me.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_narc_4",
    section: "dark_triad",
    part: 1,
    text: "I know that I am special because everyone keeps telling me so.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_narc_5",
    section: "dark_triad",
    part: 1,
    text: "I like to get acquainted with important people.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_narc_6",
    section: "dark_triad",
    part: 1,
    text: "I feel embarrassed if someone compliments me.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_narc_7",
    section: "dark_triad",
    part: 1,
    text: "I have been compared to famous people.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_narc_8",
    section: "dark_triad",
    part: 1,
    text: "I am an average person.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_narc_9",
    section: "dark_triad",
    part: 1,
    text: "I insist on getting the respect I deserve.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },

  // === Dark Triad: SD3 - Psychopathy ===
  {
    id: "sd3_psych_1",
    section: "dark_triad",
    part: 1,
    text: "I like to get revenge on authorities.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_psych_2",
    section: "dark_triad",
    part: 1,
    text: "I avoid dangerous situations.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_psych_3",
    section: "dark_triad",
    part: 1,
    text: "Payback needs to be quick and nasty.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_psych_4",
    section: "dark_triad",
    part: 1,
    text: "People often say I'm out of control.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_psych_5",
    section: "dark_triad",
    part: 1,
    text: "It's true that I can be mean to others.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_psych_6",
    section: "dark_triad",
    part: 1,
    text: "People who mess with me always regret it.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_psych_7",
    section: "dark_triad",
    part: 1,
    text: "I have never gotten into trouble with the law.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_psych_8",
    section: "dark_triad",
    part: 1,
    text: "I enjoy having sex with people I hardly know.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },
  {
    id: "sd3_psych_9",
    section: "dark_triad",
    part: 1,
    text: "I'll say anything to get what I want.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: "SD3",
  },

  // --------------------------------------------------------
  // PART 2: HOW YOU'RE DOING
  // --------------------------------------------------------

  // === Depression: PHQ-9 ===
  {
    id: "dep_phq9_1",
    section: "depression",
    part: 2,
    text: "Little interest or pleasure in doing things",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "PHQ-9",
  },
  {
    id: "dep_phq9_2",
    section: "depression",
    part: 2,
    text: "Feeling down, depressed, or hopeless",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "PHQ-9",
  },
  {
    id: "dep_phq9_3",
    section: "depression",
    part: 2,
    text: "Trouble falling or staying asleep, or sleeping too much",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "PHQ-9",
  },
  {
    id: "dep_phq9_4",
    section: "depression",
    part: 2,
    text: "Feeling tired or having little energy",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "PHQ-9",
  },
  {
    id: "dep_phq9_5",
    section: "depression",
    part: 2,
    text: "Poor appetite or overeating",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "PHQ-9",
  },
  {
    id: "dep_phq9_6",
    section: "depression",
    part: 2,
    text: "Feeling bad about yourself — or that you are a failure or have let yourself or your family down",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "PHQ-9",
  },
  {
    id: "dep_phq9_7",
    section: "depression",
    part: 2,
    text: "Trouble concentrating on things, such as reading the newspaper or watching television",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "PHQ-9",
  },
  {
    id: "dep_phq9_8",
    section: "depression",
    part: 2,
    text: "Moving or speaking so slowly that other people could have noticed? Or the opposite — being so fidgety or restless that you have been moving around a lot more than usual",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "PHQ-9",
  },
  {
    id: "dep_phq9_9",
    section: "depression",
    part: 2,
    text: "Thoughts that you would be better off dead or of hurting yourself in some way",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "PHQ-9",
  },

  // === Depression: Custom ===
  {
    id: "dep_custom_1",
    section: "depression",
    part: 2,
    text: "Which founder-specific stressors contribute most to low mood?",
    type: "multi_select",
    options: [
      "Fundraising/runway",
      "Product challenges",
      "Team issues",
      "Co-founder conflict",
      "Market uncertainty",
      "Loneliness/isolation",
      "Work-life imbalance",
      "Comparison to other founders",
      "None of these",
    ],
    required: true,
    instrument: null,
  },
  {
    id: "dep_custom_2",
    section: "depression",
    part: 2,
    text: "How much has your mood impacted your ability to run your company in the last month?",
    type: "likert5",
    options: ["Not at all", "Slightly", "Moderately", "Significantly", "Severely"],
    required: true,
    instrument: null,
  },
  {
    id: "dep_custom_3",
    section: "depression",
    part: 2,
    text: "Have you been diagnosed with depression?",
    type: "single_select",
    options: [
      "Yes - currently",
      "Yes - in the past",
      "No",
      "Suspected but not diagnosed",
    ],
    required: true,
    instrument: null,
  },

  // === Anxiety: GAD-7 ===
  {
    id: "anx_gad7_1",
    section: "anxiety",
    part: 2,
    text: "Feeling nervous, anxious, or on edge",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "GAD-7",
  },
  {
    id: "anx_gad7_2",
    section: "anxiety",
    part: 2,
    text: "Not being able to stop or control worrying",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "GAD-7",
  },
  {
    id: "anx_gad7_3",
    section: "anxiety",
    part: 2,
    text: "Worrying too much about different things",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "GAD-7",
  },
  {
    id: "anx_gad7_4",
    section: "anxiety",
    part: 2,
    text: "Trouble relaxing",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "GAD-7",
  },
  {
    id: "anx_gad7_5",
    section: "anxiety",
    part: 2,
    text: "Being so restless that it's hard to sit still",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "GAD-7",
  },
  {
    id: "anx_gad7_6",
    section: "anxiety",
    part: 2,
    text: "Becoming easily annoyed or irritable",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "GAD-7",
  },
  {
    id: "anx_gad7_7",
    section: "anxiety",
    part: 2,
    text: "Feeling afraid as if something awful might happen",
    type: "likert4",
    options: [
      "Not at all",
      "Several days",
      "More than half the days",
      "Nearly every day",
    ],
    required: true,
    instrument: "GAD-7",
  },

  // === Anxiety: Custom ===
  {
    id: "anx_custom_1",
    section: "anxiety",
    part: 2,
    text: "What are your primary anxiety triggers as a founder?",
    type: "multi_select",
    options: [
      "Fundraising/pitch meetings",
      "Runway/cash flow",
      "Team performance",
      "Co-founder disagreements",
      "Market competition",
      "Board meetings",
      "Public speaking/visibility",
      "Making wrong strategic decisions",
      "None of these",
    ],
    required: true,
    instrument: null,
  },
  {
    id: "anx_custom_2",
    section: "anxiety",
    part: 2,
    text: "How often do you experience physical anxiety symptoms (racing heart, shallow breathing, tension)?",
    type: "likert5",
    options: ["Never", "Rarely", "Sometimes", "Often", "Daily"],
    required: true,
    instrument: null,
  },
  {
    id: "anx_custom_3",
    section: "anxiety",
    part: 2,
    text: "Have you been diagnosed with an anxiety disorder?",
    type: "single_select",
    options: [
      "Yes - currently",
      "Yes - in the past",
      "No",
      "Suspected but not diagnosed",
    ],
    required: true,
    instrument: null,
  },

  // === Founder-Specific Stress ===
  {
    id: "fs_1",
    section: "founder_stress",
    part: 2,
    text: "How much stress do you experience from fundraising pressure?",
    type: "likert5",
    options: ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
    required: true,
    instrument: null,
  },
  {
    id: "fs_2",
    section: "founder_stress",
    part: 2,
    text: "How much stress do you experience from runway/cash concerns?",
    type: "likert5",
    options: ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
    required: true,
    instrument: null,
  },
  {
    id: "fs_3",
    section: "founder_stress",
    part: 2,
    text: "How much stress do you experience from co-founder conflict or tension?",
    type: "likert5",
    options: ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
    required: true,
    instrument: null,
  },
  {
    id: "fs_4",
    section: "founder_stress",
    part: 2,
    text: "How much of a problem is isolation or loneliness as a founder for you?",
    type: "likert5",
    options: ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
    required: true,
    instrument: null,
  },
  {
    id: "fs_5",
    section: "founder_stress",
    part: 2,
    text: "How often do you experience imposter syndrome?",
    type: "likert5",
    options: ["Never", "Rarely", "Sometimes", "Often", "Very Often"],
    required: true,
    instrument: null,
  },
  {
    id: "fs_6",
    section: "founder_stress",
    part: 2,
    text: "How much do you experience decision fatigue?",
    type: "likert5",
    options: ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
    required: true,
    instrument: null,
  },
  {
    id: "fs_7",
    section: "founder_stress",
    part: 2,
    text: "How much do you struggle with work-life boundary erosion?",
    type: "likert5",
    options: ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
    required: true,
    instrument: null,
  },
  {
    id: "fs_8",
    section: "founder_stress",
    part: 2,
    text: "How much stress do you experience from fear of failure or public perception?",
    type: "likert5",
    options: ["Not at all", "Slightly", "Moderately", "Very", "Extremely"],
    required: true,
    instrument: null,
  },
  {
    id: "fs_9",
    section: "founder_stress",
    part: 2,
    text: "Founding a company has negatively impacted my physical health.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: null,
  },
  {
    id: "fs_10",
    section: "founder_stress",
    part: 2,
    text: "Founding a company has negatively impacted my personal relationships.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: null,
  },

  // --------------------------------------------------------
  // PART 3: WHAT YOU'VE TRIED
  // --------------------------------------------------------

  // === Treatment & Support ===

  // Current therapy
  {
    id: "tx_therapy_current",
    section: "treatment",
    part: 3,
    text: "Are you currently seeing a therapist?",
    type: "yes_no",
    required: true,
    instrument: null,
  },
  {
    id: "tx_therapy_frequency",
    section: "treatment",
    part: 3,
    text: "How often do you see your therapist?",
    type: "single_select",
    options: ["Weekly", "Biweekly", "Monthly", "As needed"],
    required: true,
    instrument: null,
    conditionalOn: "tx_therapy_current",
    conditionalValue: "Yes",
  },
  {
    id: "tx_therapy_modality",
    section: "treatment",
    part: 3,
    text: "What modality of therapy?",
    type: "single_select",
    options: ["CBT", "Psychodynamic", "EMDR", "Somatic", "DBT", "Other", "Unsure"],
    required: true,
    instrument: null,
    conditionalOn: "tx_therapy_current",
    conditionalValue: "Yes",
  },
  {
    id: "tx_therapy_helpful",
    section: "treatment",
    part: 3,
    text: "How helpful has therapy been?",
    type: "likert5",
    options: [
      "Not helpful",
      "Slightly helpful",
      "Moderately helpful",
      "Very helpful",
      "Extremely helpful",
    ],
    required: true,
    instrument: null,
    conditionalOn: "tx_therapy_current",
    conditionalValue: "Yes",
  },

  // Current coaching
  {
    id: "tx_coach_current",
    section: "treatment",
    part: 3,
    text: "Are you currently seeing a coach?",
    type: "yes_no",
    required: true,
    instrument: null,
  },
  {
    id: "tx_coach_type",
    section: "treatment",
    part: 3,
    text: "What type of coach?",
    type: "single_select",
    options: [
      "Executive coach",
      "Life coach",
      "Somatic coach",
      "Peer group (YPO/EO/etc.)",
      "Other",
    ],
    required: true,
    instrument: null,
    conditionalOn: "tx_coach_current",
    conditionalValue: "Yes",
  },
  {
    id: "tx_coach_helpful",
    section: "treatment",
    part: 3,
    text: "How helpful has coaching been?",
    type: "likert5",
    options: [
      "Not helpful",
      "Slightly helpful",
      "Moderately helpful",
      "Very helpful",
      "Extremely helpful",
    ],
    required: true,
    instrument: null,
    conditionalOn: "tx_coach_current",
    conditionalValue: "Yes",
  },

  // Current medication
  {
    id: "tx_medication_current",
    section: "treatment",
    part: 3,
    text: "Are you currently on medication for mental health?",
    type: "yes_no",
    required: true,
    instrument: null,
  },
  {
    id: "tx_medication_types",
    section: "treatment",
    part: 3,
    text: "Which categories of medication?",
    type: "multi_select",
    options: [
      "SSRI",
      "SNRI",
      "Stimulant",
      "Anxiolytic",
      "Mood stabilizer",
      "Other",
    ],
    required: true,
    instrument: null,
    conditionalOn: "tx_medication_current",
    conditionalValue: "Yes",
  },
  {
    id: "tx_medication_effective",
    section: "treatment",
    part: 3,
    text: "How effective has medication been?",
    type: "likert5",
    options: [
      "Not effective",
      "Slightly effective",
      "Moderately effective",
      "Very effective",
      "Extremely effective",
    ],
    required: true,
    instrument: null,
    conditionalOn: "tx_medication_current",
    conditionalValue: "Yes",
  },
  {
    id: "tx_medication_side_effects",
    section: "treatment",
    part: 3,
    text: "How much do side effects impact your daily functioning?",
    type: "likert5",
    options: [
      "No impact",
      "Slight impact",
      "Moderate impact",
      "Significant impact",
      "Severe impact",
    ],
    required: true,
    instrument: null,
    conditionalOn: "tx_medication_current",
    conditionalValue: "Yes",
  },

  // Other current treatments
  {
    id: "tx_other_current",
    section: "treatment",
    part: 3,
    text: "Are you currently using any of these?",
    type: "multi_select",
    options: [
      "Meditation/mindfulness apps",
      "Support groups",
      "Peer counseling",
      "Journaling",
      "Breathwork",
      "Psychedelics",
      "None of these",
    ],
    required: true,
    instrument: null,
  },

  // Past therapy
  {
    id: "tx_therapy_past",
    section: "treatment",
    part: 3,
    text: "Have you ever seen a therapist?",
    type: "yes_no",
    required: true,
    instrument: null,
  },
  {
    id: "tx_therapy_stop_reason",
    section: "treatment",
    part: 3,
    text: "Why did you stop seeing a therapist?",
    type: "multi_select",
    options: [
      "Cost",
      "Felt better",
      "Not helpful",
      "Scheduling",
      "Therapist fit",
      "Other",
    ],
    required: true,
    instrument: null,
    conditionalOn: "tx_therapy_past",
    conditionalValue: "Yes",
  },
  {
    id: "tx_therapy_past_value",
    section: "treatment",
    part: 3,
    text: "Overall, how valuable was past therapy?",
    type: "likert5",
    options: [
      "Not valuable",
      "Slightly valuable",
      "Moderately valuable",
      "Very valuable",
      "Extremely valuable",
    ],
    required: true,
    instrument: null,
    conditionalOn: "tx_therapy_past",
    conditionalValue: "Yes",
  },

  // Past coaching
  {
    id: "tx_coach_past",
    section: "treatment",
    part: 3,
    text: "Have you ever seen a coach?",
    type: "yes_no",
    required: true,
    instrument: null,
  },
  {
    id: "tx_coach_stop_reason",
    section: "treatment",
    part: 3,
    text: "Why did you stop seeing a coach?",
    type: "multi_select",
    options: [
      "Cost",
      "Felt better",
      "Not helpful",
      "Scheduling",
      "Coach fit",
      "Engagement ended",
      "Other",
    ],
    required: true,
    instrument: null,
    conditionalOn: "tx_coach_past",
    conditionalValue: "Yes",
  },
  {
    id: "tx_coach_past_value",
    section: "treatment",
    part: 3,
    text: "Overall, how valuable was past coaching?",
    type: "likert5",
    options: [
      "Not valuable",
      "Slightly valuable",
      "Moderately valuable",
      "Very valuable",
      "Extremely valuable",
    ],
    required: true,
    instrument: null,
    conditionalOn: "tx_coach_past",
    conditionalValue: "Yes",
  },

  // Past medication
  {
    id: "tx_medication_past",
    section: "treatment",
    part: 3,
    text: "Have you ever taken medication for mental health?",
    type: "yes_no",
    required: true,
    instrument: null,
  },
  {
    id: "tx_medication_stop_reason",
    section: "treatment",
    part: 3,
    text: "Why did you stop taking medication?",
    type: "multi_select",
    options: [
      "Side effects",
      "Felt better",
      "Cost",
      "Didn't help",
      "Preferred non-medication approach",
      "Other",
    ],
    required: true,
    instrument: null,
    conditionalOn: "tx_medication_past",
    conditionalValue: "Yes",
  },
  {
    id: "tx_medication_past_value",
    section: "treatment",
    part: 3,
    text: "Overall, how valuable was past medication?",
    type: "likert5",
    options: [
      "Not valuable",
      "Slightly valuable",
      "Moderately valuable",
      "Very valuable",
      "Extremely valuable",
    ],
    required: true,
    instrument: null,
    conditionalOn: "tx_medication_past",
    conditionalValue: "Yes",
  },

  // Crisis history
  {
    id: "tx_crisis_hotline",
    section: "treatment",
    part: 3,
    text: "Have you ever used a crisis hotline or emergency mental health service?",
    type: "yes_no",
    required: true,
    instrument: null,
  },
  {
    id: "tx_hospitalized",
    section: "treatment",
    part: 3,
    text: "Have you ever been hospitalized for mental health?",
    type: "yes_no",
    required: true,
    instrument: null,
  },

  // Barriers and beliefs
  {
    id: "tx_barriers",
    section: "treatment",
    part: 3,
    text: "What are your current barriers to seeking mental health support?",
    type: "multi_select",
    options: [
      "Cost",
      "Stigma",
      "Time",
      "It's not that bad",
      "Don't know where to start",
      "Tried before and it didn't help",
      "Concern about confidentiality",
      "Worry about perception from investors/board/team",
      "No barriers",
      "Other",
    ],
    required: true,
    instrument: null,
  },
  {
    id: "tx_belief_worth",
    section: "treatment",
    part: 3,
    text: "I believe therapy/coaching is worth the investment.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: null,
  },
  {
    id: "tx_comfort_disclosure",
    section: "treatment",
    part: 3,
    text: "I would be comfortable telling my co-founder or team that I see a therapist.",
    type: "likert5",
    options: [
      "Strongly Disagree",
      "Disagree",
      "Neither Agree nor Disagree",
      "Agree",
      "Strongly Agree",
    ],
    required: true,
    instrument: null,
  },
];

// ============================================================
// Helper Functions
// ============================================================

export function getQuestionsBySection(sectionId: SectionId): Question[] {
  return QUESTIONS.filter((q) => q.section === sectionId);
}
